# Generated by Django 5.0.3 on 2024-03-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder', models.PositiveIntegerField(help_text='Papkasi', verbose_name='Papka')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, help_text='Telegram user_id')),
                ('first_name', models.CharField(help_text='Akkaunt nomi first_name', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='Akkaunt nomi last_name', max_length=255, null=True)),
                ('username', models.CharField(blank=True, help_text='Akkaunt @username', max_length=255, null=True)),
                ('phone_number', models.PositiveBigIntegerField(help_text='Akkaunt telefon raqami')),
                ('is_spam', models.BooleanField(default=False, help_text="Spam bo'lganmi yo'qmi")),
                ('string_session', models.TextField(help_text='Telethon uchun string session')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(help_text='Kanalning telegram chat_id raqami')),
                ('name', models.CharField(help_text='Kanal nomi', max_length=255)),
                ('invite_link', models.CharField(help_text="Kanal linki qo'shilish uchun", max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, help_text='Kanal ochilgan vaqt')),
                ('creator', models.ForeignKey(help_text='Kanalni ochgan akkaunt', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(help_text='Guruhning telegram chat_id raqami')),
                ('name', models.CharField(help_text='Guruh nomi', max_length=255)),
                ('invite_link', models.CharField(help_text="Guruh linki qo'shilish uchun", max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, help_text='Guruh ochilgan vaqt')),
                ('creator', models.ForeignKey(help_text='Guruhni ochgan akkaunt', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
    ]
